---
title: ""
author: "Cazalé-Debat et al. 2023"
output:
  html_document:
    df_print: paged
    word_document: default
    pdf_document: default
  pdf_document: default
---

```{r start, include=FALSE}
rm(list=ls())
data<-read.delim("/Users/cazaledl-admin/Library/CloudStorage/OneDrive-UniversityofBirmingham/Post_doc/XP/data/courtscape/screen/text/.txt",h=T,sep="\t",na.strings = "NA", stringsAsFactors=T)

library(beeswarm)
library(conover.test)
library(knitr)
library(tinytex)
attach(data)

data$newvar <- character(nrow(data))
data$newvar[data$line == ""]      <- "gal4line"     
data$newvar[data$line == ""]       <- "uasline"       
data$newvar[data$line == ""] <- "xp_line"         
attach(data)
```

```{r}
# OPTOGENETIC EXPERIMENT : COURTSHIP INDEX (CI)
```

```{r summary data, echo=FALSE, paged.print=TRUE}
a<-summary(CI[which(newvar=='gal4line' & status_light=='OFF'])
b<-length(CI[which(newvar=='gal4line' & status_light=='OFF'])
data1<-matrix(c(a,b))
colnames(data1)<-'gal4_lightoff'
rownames(data1)<-c(names(a), 'sample_size')

d<-summary(CI[which(newvar=='uasline' & status_light=='OFF'])
e<-length(CI[which(newvar=='uasline' & status_light=='OFF'])
data2<-matrix(c(d,e))
colnames(data2)<-'uas_lightoff'

f<-summary(CI[which(newvar=='xp_line' & status_light=='OFF'])
g<-length(CI[which(newvar=='xp_line' & status_light=='OFF'])
data3<-matrix(c(f,g))
colnames(data3)<-'xp_lightoff'
alldata_lightoff<-cbind(data1,data2,data3)

h<-summary(CI[which(newvar=='gal4line' & status_light=='ON'])
i<-length(CI[which(newvar=='gal4line' & status_light=='ON'])
data4<-matrix(c(h,i))
colnames(data4)<-'gal4_lighton'

j<-summary(CI[which(newvar=='uasline' & status_light=='ON'])
k<-length(CI[which(newvar=='uasline' & status_light=='ON'])
data5<-matrix(c(j,k))
colnames(data5)<-'uas_lighton'

f<-summary(CI[which(newvar=='xp_line' & status_light=='ON'])
g<-length(CI[which(newvar=='xp_line' & status_light=='ON'])
data6<-matrix(c(f,g))
colnames(data6)<-'xp_lighton'
alldata_lighton<-cbind(data4,data5,data6)

alldata<-cbind(alldata_lightoff,alldata_lighton)
kable(alldata[c(-1,-6),], caption = "courtship index - summary by line and treatment")

```

```{r}
# LIGHT OFF 
```

```{r include=FALSE}
courtship_index_LIGHTOFF <- 
     c(CI  [which(threat=="ETNT" & newvar=="gal4line")],
       CI  [which(threat=="ETNT" & newvar=="uasline")],
       CI  [which(threat=="ETNT" & newvar=="xp_line")])

line_LIGHTOFF_treatment <- factor(rep(1:3, 
                                      
                     c(length(CI  [which(threat=="ETNT" & newvar=="gal4line")]), 
                       length(CI  [which(threat=="ETNT" & newvar=="uasline")]),
                       length(CI  [which(threat=="ETNT" & newvar=="xp_line")])),
                  
            labels = c(
              "CI_gal4line; light off",
              "CI_uasline; ; light off",
              "CI_xp_line; light off")))


courtship_index_LIGHTON <- 
     c(CI  [which(threat=="ET" & newvar=="gal4line")],
       CI  [which(threat=="ET" & newvar=="uasline")],
       CI  [which(threat=="ET" & newvar=="xp_line")])

line_LIGHTON_treatment <- factor(rep(1:3, 
                                      
                     c(length(CI  [which(threat=="ET" & newvar=="gal4line")]), 
                       length(CI  [which(threat=="ET" & newvar=="uasline")]),
                       length(CI  [which(threat=="ET" & newvar=="xp_line")])),
                  
            labels = c(
              "CI_gal4line; light ON",
              "CI_uasline; ; light ON",
              "CI_xp_line; light ON")))
```

```{r OPTOGENETIC ONLY - Courtship index  LIGHT OFF, echo=FALSE, comment=NA}

kruskal.test(data$CI[which(threat=="ETNT")] ~ data$line[which(threat=="ETNT")])
```

```{r conover.test Courtship index LIGHT OFF, echo=FALSE, comment=NA}
             conover.test(
             courtship_index_LIGHTOFF, 
             line_LIGHTOFF_treatment, 
             method="bonferroni", 
             list=TRUE, table=F, kw=F)
```

```{r}
# LIGHT ON 
```

```{r OPTOGENETIC ONLY - Courtship index LIGHT ON, echo=FALSE, comment=NA}
kruskal.test(data$CI[which(threat=="ET")] ~ data$line[which(threat=="ET")])
```

```{r conover.test Courtship index LIGHT ON, echo=FALSE,comment=NA}
conover.test(courtship_index_LIGHTON, line_LIGHTON_treatment, method="bonferroni", list=TRUE, table=F, kw=F )

```

```{r}
# OPTOGENETIC EXPERIMENT : DEFENSIVE INDEX (DI)
```

```{r summary data defensive index, echo=FALSE, paged.print=TRUE}
a<-summary(DI[which(newvar=='gal4line' & status_light=='OFF'])
b<-length(DI[which(newvar=='gal4line' & status_light=='OFF'])
data1<-matrix(c(a,b))
colnames(data1)<-'gal4_lightoff'
rownames(data1)<-c(names(a), 'sample_size')

d<-summary(DI[which(newvar=='uasline' & status_light=='OFF'])
e<-length(DI[which(newvar=='uasline' & status_light=='OFF'])
data2<-matrix(c(d,e))
colnames(data2)<-'uas_lightoff'

f<-summary(DI[which(newvar=='xp_line' & status_light=='OFF'])
g<-length(DI[which(newvar=='xp_line' & status_light=='OFF'])
data3<-matrix(c(f,g))
colnames(data3)<-'xp_lightoff'
alldata_lightoff<-cbind(data1,data2,data3)

h<-summary(DI[which(newvar=='gal4line' & status_light=='ON'])
i<-length(DI[which(newvar=='gal4line' & status_light=='ON'])
data4<-matrix(c(h,i))
colnames(data4)<-'gal4_lighton'

j<-summary(DI[which(newvar=='uasline' & status_light=='ON'])
k<-length(DI[which(newvar=='uasline' & status_light=='ON'])
data5<-matrix(c(j,k))
colnames(data5)<-'uas_lighton'

f<-summary(DI[which(newvar=='xp_line' & status_light=='ON'])
g<-length(DI[which(newvar=='xp_line' & status_light=='ON'])
data6<-matrix(c(f,g))
colnames(data6)<-'xp_lighton'
alldata_lighton<-cbind(data4,data5,data6)

alldata<-cbind(alldata_lightoff,alldata_lighton)
kable(alldata[c(-1,-6),], caption = "defensive index - summary by line and treatment")

```
```{r}
# LIGHT OFF 
```


```{r include=FALSE}
defensive_index_LIGHTOFF <- 
     c(DI  [which(threat=="ETNT" & newvar=="gal4line")],
       DI  [which(threat=="ETNT" & newvar=="uasline")],
       DI  [which(threat=="ETNT" & newvar=="xp_line")])

line_LIGHTOFF_treatment <- factor(rep(1:3, 
                                      
                     c(length(DI  [which(threat=="ETNT" & newvar=="gal4line")]), 
                       length(DI  [which(threat=="ETNT" & newvar=="uasline")]),
                       length(DI  [which(threat=="ETNT" & newvar=="xp_line")])),
                  
            labels = c(
              "DI_gal4line; light off",
              "DI_uasline; ; light off",
              "DI_xp_line; light off")))


defensive_index_LIGHTON <- 
     c(DI  [which(threat=="ET" & newvar=="gal4line")],
       DI  [which(threat=="ET" & newvar=="uasline")],
       DI  [which(threat=="ET" & newvar=="xp_line")])

line_LIGHTON_treatment <- factor(rep(1:3, 
                                      
                     c(length(DI  [which(threat=="ET" & newvar=="gal4line")]), 
                       length(DI  [which(threat=="ET" & newvar=="uasline")]),
                       length(DI  [which(threat=="ET" & newvar=="xp_line")])),
                  
            labels = c(
              "DI_gal4line; light ON",
              "DI_uasline; ; light ON",
              "DI_xp_line; light ON")))
```

```{r OPTOGENETIC ONLY - Defensive index  LIGHT OFF, echo=FALSE,comment=NA}
kruskal.test(data$DI[which(threat=="ETNT")] ~ data$line[which(threat=="ETNT")])
```

```{r conover.test Defensive index LIGHT OFF, echo=FALSE,comment=NA}
conover.test(defensive_index_LIGHTOFF, 
             line_LIGHTOFF_treatment, 
             method="bonferroni", 
             list=TRUE, table=F, kw=F )
```

```{r}
# LIGHT ON 
```

```{r OPTOGENETIC ONLY - Defensive index LIGHT ON, echo=FALSE,comment=NA}
kruskal.test(data$DI[which(threat=="ET")] ~ data$line[which(threat=="ET")])
```

```{r conover.test Defensive index LIGHT ON, echo=FALSE,comment=NA}
conover.test(defensive_index_LIGHTON, line_LIGHTON_treatment, method="bonferroni", list=TRUE, table=F, kw=F )
```